name: Deploy NexusTradeAI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'services/**'
      - 'clients/**'
      - 'infrastructure/**'
      - '.github/workflows/**'

  pull_request:
    branches:
      - main
    paths:
      - 'services/**'
      - 'clients/**'
      - 'infrastructure/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      force_deploy:
        description: 'Force deployment even if tests fail'
        required: false
        default: false
        type: boolean

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
  CLUSTER_NAME: nexustrade-ai-${{ github.ref_name == 'main' && 'production' || 'staging' }}
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  # Determine deployment environment
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
      deploy_infrastructure: ${{ steps.changes.outputs.infrastructure }}
      deploy_services: ${{ steps.changes.outputs.services }}
      deploy_clients: ${{ steps.changes.outputs.clients }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            infrastructure:
              - 'infrastructure/**'
            services:
              - 'services/**'
            clients:
              - 'clients/**'